package es.seas.feedback.cliente.manager.view;

import es.seas.feedback.cliente.manager.control.PersonaControl;
import javax.swing.JTable;
import javax.swing.table.TableModel;

/**
 * Esta clase es una tabla para persona.
 * @author Ricardo Maximino
 * <p>Este clase extende JInternalFrame y dentro de este JInternalFrame
 * hay solamente un componente visual(JTable).</p>
 */
public class ListaPersona extends javax.swing.JInternalFrame {
    private PersonaControl<?> control;

    /**
     * Este es el constructor sin argumentos, lo cual solamente inicia los 
     * componentes.
     */
    public ListaPersona() {
        initComponents();
    }
    /**
     * Este constructor ademas que iniciar lo componentes configura el model
     * de la JTable.
     * @param model del tipo javax.swing.table.TableModel.
     */
    public ListaPersona(TableModel model){
        this();
        tabla.setModel(model);
    }
    
    /**
     * Este metodo retorna el valor de la variable global tabla.
     * @return del tipo javax.swing.JTable.
     */
    public JTable getTabla() {
        return tabla;
    }

    /**
     * Este metodo configura la variable global tabla.
     * @param tabla del tipo javax.swing.JTable.
     */
    public void setTabla(JTable tabla) {
        this.tabla = tabla;
    }
    
    /**
     * Este metodo retorna el valor de la variable global control.
     * @return del tipo es.seas.feedback.cliente.manager.control.PersonaControl.
     */
    public PersonaControl<?> getControl() {
        return control;
    }

    /**
     * Este metodo configura la variable global control.
     * @param control del tipo 
     * es.seas.feedback.cliente.manager.control.PersonaControl.
     */
    public void setControl(PersonaControl<?> control) {
        this.control = control;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(800, 600));
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                formComponentHidden(evt);
            }
        });

        tabla.setAutoCreateRowSorter(true);
        tabla.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tabla.setToolTipText("Hga doble clic para editar");
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tablaMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tabla);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked
    
    }//GEN-LAST:event_tablaMouseClicked

    private void tablaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMousePressed
        if(evt.getClickCount()== 2){
            int row = tabla.getSelectedRow();
            String nif = tabla.getValueAt(row, 1).toString();
            control.crearFrameAtualizar(nif);
        }
    }//GEN-LAST:event_tablaMousePressed

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
      // TODO add your handling code here:
    }//GEN-LAST:event_formFocusGained

    private void formComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentHidden

    }//GEN-LAST:event_formComponentHidden

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
      
    }//GEN-LAST:event_formInternalFrameClosing

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
