/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package es.seas.feedback.cliente.manager.view.cliente;


import es.seas.feedback.cliente.manager.control.ClienteControl;
import es.seas.feedback.cliente.manager.view.PersonaUtilidades;

/**
 *
 * @author Ricardo
 */
public class BuscarCliente extends javax.swing.JDialog {

    private ClienteControl control;
    //No se porque pero si entento comprobar se if(control.getPersonaUtilidades()!= null) me sale un NullPointerException
    //por eso estoy inyectando por constructor
    private PersonaUtilidades personaUtilidades;
    /**
     * Creates new form BuscarCliente
     * @param parent
     * @param modal 
     * @param personUtilidades 
     */
    public BuscarCliente(java.awt.Frame parent, boolean modal,PersonaUtilidades personUtilidades) {
        super(parent, modal);
        initComponents();
        this.personaUtilidades = personUtilidades;
        cmbCamposCliente.setModel(personaUtilidades.camposPersonaComboModel());//control.getPersonaUtilidades().camposPersonaComboModel());
    }

    public ClienteControl getControl() {
        return control;
    }

    public void setControl(ClienteControl control) {
        this.control = control;
    }

    public void clear(){
        txtBuscar.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCampo = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        cmbCamposCliente = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblCampo.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("es/seas/feedback/cliente/manager/view/internationalization/view"); // NOI18N
        lblCampo.setText(bundle.getString("label_SearchFor")); // NOI18N

        txtBuscar.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });
        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBuscarKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscarKeyTyped(evt);
            }
        });

        btnBuscar.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        btnBuscar.setText(bundle.getString("button_Search")); // NOI18N
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        cmbCamposCliente.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        cmbCamposCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCamposClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCampo)
                        .addGap(18, 18, 18)
                        .addComponent(cmbCamposCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txtBuscar)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbCamposCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyTyped

    }//GEN-LAST:event_txtBuscarKeyTyped

    private void txtBuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyPressed
       if(evt.getKeyCode() == 10){
           this.dispose();
           buscar();
       }
    }//GEN-LAST:event_txtBuscarKeyPressed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        dispose();  buscar();   
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void cmbCamposClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCamposClienteActionPerformed
        if(cmbCamposCliente.getSelectedItem().toString().equals(personaUtilidades.getCamposPersona()[5])||
                cmbCamposCliente.getSelectedItem().toString().equals(personaUtilidades.getCamposPersona()[4])){
            txtBuscar.setEnabled(false);
        }else{
            txtBuscar.setEnabled(true);
        }
    }//GEN-LAST:event_cmbCamposClienteActionPerformed

    public void buscar(){   
        control.buscar(cmbCamposCliente.getSelectedItem().toString(), txtBuscar.getText());  
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JComboBox<String> cmbCamposCliente;
    private javax.swing.JLabel lblCampo;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
