/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package es.seas.feedback.cliente.manager.view;

import javax.swing.JDesktopPane;
import javax.swing.JInternalFrame;
import es.seas.feedback.cliente.manager.control.PersonaControl;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.ResourceBundle;

/**
 *
 * @author Ricardo
 */
public class VentanaPrincipal extends javax.swing.JFrame implements Controlable {
    private int x = 0;
    private int y = 0;
    private PersonaControl clienteControl;
    private PersonaControl usuarioControl;

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }
    public VentanaPrincipal(PersonaControl clienteController){
        this();
        this.clienteControl = clienteController;       
    }
    @Override
    public JDesktopPane getDesktopPane() {
        return desktopPane;
    }

    public void setDesktopPane(JDesktopPane desktopPane) {
        this.desktopPane = desktopPane;
    }
    
    private int getPositionX(){
        x += 30;
        if(desktopPane.getWidth()-800<x){
            x= 0;
        }
        return x;
    }
    private int getPositionY(){
        y += 30;
        if(this.desktopPane.getHeight()-120< y){
            y=0;
        }
        return y;
    }
    private void restartXY(){
        x=y=0;
    }
    @Override
    public void showInternalFrame(JInternalFrame frame){    
        if(desktopPane.getAllFrames().length==0) restartXY();
        
        frame.setClosable(true);
        frame.setIconifiable(true);
        frame.setResizable(false);
        
        desktopPane.add(frame);
        frame.setLocation(getPositionX(), getPositionY());
        frame.setVisible(true);
    }
    
    @Override
    public void setClienteControl(PersonaControl control){
        this.clienteControl = control;
    }
    public PersonaControl getClienteControl(){
        return clienteControl;
    }

    @Override
    public void setUsuarioControl(PersonaControl control) {
        this.usuarioControl = control;
    }
    public PersonaControl getUsuarioControl(){
        return usuarioControl;
    }
    
    private void reset(){
        for(JInternalFrame f: desktopPane.getAllFrames()){
            f.dispose();
        }
        restartXY();
        clienteControl.getPersonaUtilidades().refresh();
        ResourceBundle view = ResourceBundle.getBundle("es.seas.feedback.cliente.manager.view.internationalization.view");
        //Cliente
        menuCliente.setText(view.getString("menu_Client"));
        menuItemBuscarCliente.setText(view.getString("menuItem_SearchClient"));
        menuItemListarTodosCliente.setText(view.getString("menuItem_ListAll"));
        menuItemNuevoCliente.setText(view.getString("menuItem_NewClient"));
        //Ventanas
        menuVentanas.setText(view.getString("menu_Windows"));
        menuItemCerrar.setText(view.getString("menuItem_Close"));
        menuItemCerrarTodo.setText(view.getString("menuItem_CloseAll"));
        menuItemCascada.setText(view.getString("menuItem_Waterfall"));
        //Usuario
        menuUsuario.setText(view.getString("menu_User"));
        menuItemBuscarUsuario.setText(view.getString("menuItem_SearchUser"));
        menuItemListarTodosUsuario.setText(view.getString("menuItem_ListAll"));
        menuItemNuevoUsuario.setText(view.getString("menuItem_NewUser"));
        //Lenguas
        menuLengua.setText(view.getString("menu_Languages"));
        menuItemCastellano.setText(view.getString("menuItem_Spanish"));
        menuItemIngles.setText(view.getString("menuItem_English"));
        menuItemPortugues.setText(view.getString("menuItem_Portugues"));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        menuCliente = new javax.swing.JMenu();
        menuItemBuscarCliente = new javax.swing.JMenuItem();
        menuItemListarTodosCliente = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuItemNuevoCliente = new javax.swing.JMenuItem();
        menuVentanas = new javax.swing.JMenu();
        menuItemCerrar = new javax.swing.JMenuItem();
        menuItemCerrarTodo = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        menuItemCascada = new javax.swing.JMenuItem();
        menuUsuario = new javax.swing.JMenu();
        menuItemBuscarUsuario = new javax.swing.JMenuItem();
        menuItemListarTodosUsuario = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        menuItemNuevoUsuario = new javax.swing.JMenuItem();
        menuLengua = new javax.swing.JMenu();
        menuItemCastellano = new javax.swing.JMenuItem();
        menuItemIngles = new javax.swing.JMenuItem();
        menuItemPortugues = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(850, 650));

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 731, Short.MAX_VALUE)
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 487, Short.MAX_VALUE)
        );

        getContentPane().add(desktopPane, java.awt.BorderLayout.CENTER);

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("es/seas/feedback/cliente/manager/view/internationalization/view"); // NOI18N
        menuCliente.setText(bundle.getString("menu_Client")); // NOI18N

        menuItemBuscarCliente.setText(bundle.getString("menuItem_SearchClient")); // NOI18N
        menuItemBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemBuscarClienteActionPerformed(evt);
            }
        });
        menuCliente.add(menuItemBuscarCliente);

        menuItemListarTodosCliente.setText(bundle.getString("menuItem_ListAll")); // NOI18N
        menuItemListarTodosCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemListarTodosClienteActionPerformed(evt);
            }
        });
        menuCliente.add(menuItemListarTodosCliente);
        menuCliente.add(jSeparator1);

        menuItemNuevoCliente.setText(bundle.getString("menuItem_NewClient")); // NOI18N
        menuItemNuevoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemNuevoClienteActionPerformed(evt);
            }
        });
        menuCliente.add(menuItemNuevoCliente);

        menuBar.add(menuCliente);

        menuVentanas.setText(bundle.getString("menu_Windows")); // NOI18N

        menuItemCerrar.setText(bundle.getString("menuItem_Close")); // NOI18N
        menuItemCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCerrarActionPerformed(evt);
            }
        });
        menuVentanas.add(menuItemCerrar);

        menuItemCerrarTodo.setText(bundle.getString("menuItem_CloseAll")); // NOI18N
        menuItemCerrarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCerrarTodoActionPerformed(evt);
            }
        });
        menuVentanas.add(menuItemCerrarTodo);
        menuVentanas.add(jSeparator2);

        menuItemCascada.setText(bundle.getString("menuItem_Waterfall")); // NOI18N
        menuItemCascada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCascadaActionPerformed(evt);
            }
        });
        menuVentanas.add(menuItemCascada);

        menuBar.add(menuVentanas);

        menuUsuario.setText(bundle.getString("menu_User")); // NOI18N
        menuUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuUsuarioActionPerformed(evt);
            }
        });

        menuItemBuscarUsuario.setText(bundle.getString("menuItem_SearchUser")); // NOI18N
        menuItemBuscarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemBuscarUsuarioActionPerformed(evt);
            }
        });
        menuUsuario.add(menuItemBuscarUsuario);

        menuItemListarTodosUsuario.setText(bundle.getString("menuItem_ListAll")); // NOI18N
        menuItemListarTodosUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemListarTodosUsuarioActionPerformed(evt);
            }
        });
        menuUsuario.add(menuItemListarTodosUsuario);
        menuUsuario.add(jSeparator3);

        menuItemNuevoUsuario.setText(bundle.getString("menuItem_NewUser")); // NOI18N
        menuItemNuevoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemNuevoUsuarioActionPerformed(evt);
            }
        });
        menuUsuario.add(menuItemNuevoUsuario);

        menuBar.add(menuUsuario);

        menuLengua.setText(bundle.getString("menu_Languages")); // NOI18N

        menuItemCastellano.setText(bundle.getString("menuItem_Spanish")); // NOI18N
        menuItemCastellano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCastellanoActionPerformed(evt);
            }
        });
        menuLengua.add(menuItemCastellano);

        menuItemIngles.setText(bundle.getString("menuItem_English")); // NOI18N
        menuItemIngles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemInglesActionPerformed(evt);
            }
        });
        menuLengua.add(menuItemIngles);

        menuItemPortugues.setText(bundle.getString("menuItem_Portugues")); // NOI18N
        menuItemPortugues.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemPortuguesActionPerformed(evt);
            }
        });
        menuLengua.add(menuItemPortugues);

        menuBar.add(menuLengua);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemNuevoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemNuevoClienteActionPerformed
        clienteControl.crearFrameAñadir();
    }//GEN-LAST:event_menuItemNuevoClienteActionPerformed

    
    private void menuItemBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemBuscarClienteActionPerformed
        clienteControl.crearFrameBuscar();
    }//GEN-LAST:event_menuItemBuscarClienteActionPerformed

    private void menuItemCascadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCascadaActionPerformed
        restartXY();
        for(JInternalFrame frame : desktopPane.getAllFrames()){
            frame.setLocation(getPositionX(), getPositionY());
        }
    }//GEN-LAST:event_menuItemCascadaActionPerformed

    private void menuItemCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCerrarActionPerformed
       JInternalFrame frame = desktopPane.getSelectedFrame();
       if(frame != null){
           clienteControl.closeFrame(frame);
           usuarioControl.closeFrame(frame);
           frame.dispose();
       }
    }//GEN-LAST:event_menuItemCerrarActionPerformed

    private void menuItemCerrarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCerrarTodoActionPerformed
        for(JInternalFrame frame : desktopPane.getAllFrames()){
            clienteControl.closeFrame(frame);
            usuarioControl.closeFrame(frame);
            frame.dispose();
        }
    }//GEN-LAST:event_menuItemCerrarTodoActionPerformed

    private void menuItemListarTodosClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemListarTodosClienteActionPerformed
        clienteControl.listarTodos();
    }//GEN-LAST:event_menuItemListarTodosClienteActionPerformed

    private void menuItemBuscarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemBuscarUsuarioActionPerformed
        usuarioControl.crearFrameBuscar();
    }//GEN-LAST:event_menuItemBuscarUsuarioActionPerformed

    private void menuItemListarTodosUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemListarTodosUsuarioActionPerformed
        usuarioControl.listarTodos();
    }//GEN-LAST:event_menuItemListarTodosUsuarioActionPerformed

    private void menuItemNuevoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemNuevoUsuarioActionPerformed
        usuarioControl.crearFrameAñadir();
    }//GEN-LAST:event_menuItemNuevoUsuarioActionPerformed

    private void menuUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuUsuarioActionPerformed
        
    }//GEN-LAST:event_menuUsuarioActionPerformed

    private void menuItemCastellanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCastellanoActionPerformed
        Locale.setDefault(new Locale("es"));
        reset();
    }//GEN-LAST:event_menuItemCastellanoActionPerformed

    private void menuItemInglesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemInglesActionPerformed
        Locale.setDefault(Locale.ENGLISH);
        reset();
    }//GEN-LAST:event_menuItemInglesActionPerformed

    private void menuItemPortuguesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemPortuguesActionPerformed
        Locale.setDefault(new Locale("pt"));
        reset();
    }//GEN-LAST:event_menuItemPortuguesActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuCliente;
    private javax.swing.JMenuItem menuItemBuscarCliente;
    private javax.swing.JMenuItem menuItemBuscarUsuario;
    private javax.swing.JMenuItem menuItemCascada;
    private javax.swing.JMenuItem menuItemCastellano;
    private javax.swing.JMenuItem menuItemCerrar;
    private javax.swing.JMenuItem menuItemCerrarTodo;
    private javax.swing.JMenuItem menuItemIngles;
    private javax.swing.JMenuItem menuItemListarTodosCliente;
    private javax.swing.JMenuItem menuItemListarTodosUsuario;
    private javax.swing.JMenuItem menuItemNuevoCliente;
    private javax.swing.JMenuItem menuItemNuevoUsuario;
    private javax.swing.JMenuItem menuItemPortugues;
    private javax.swing.JMenu menuLengua;
    private javax.swing.JMenu menuUsuario;
    private javax.swing.JMenu menuVentanas;
    // End of variables declaration//GEN-END:variables
}
